version: '3'
services:
  m2hub-east-service:
    image: python:3.11-rc-slim-buster
    tty: true
    volumes:
      - ./src:/go/src
    command: "python3 -m http.server 8080"
    networks:
      - mock-link
    
  m2hub-west-service:
    image: python:3.11-rc-slim-buster
    tty: true
    volumes:
      - ./src:/go/src
    command: "python3 -m http.server 8080"
    networks:
      - mock-link
    
  m2hub-us-service:
    image: python:3.11-rc-slim-buster
    tty: true
    volumes:
      - ./src:/go/src
    command: "python3 -m http.server 8080"
    networks:
      - mock-link
    

      
networks:
  mock-link:
    name: mock-net

    
