name: "custome action"

inputs:
  name:
    description: "sample"
    required: true

runs:
  using: "composite"
  steps:
    - name: "hello"
      run: echo "hello custome action!!!!!!"
      
    - name: "hello"
      run: echo ${{ inputs.name }}
      
