name: call_job
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: hello
        run: echo "call job origin"
        
      - name: common
        uses: ./.github/actions/first-step
        with:
          name: "call_job_step!!!!!!!"

  
  call:
    needs: [setup]
    uses: ./.github/workflows/common.yaml
    with:
      name: "call_job!!!!!!"
  
