name: call_job
on: [push]

jobs:
  custome-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: common
        uses: ./.github/workflows/first-step


  call-job:
    needs: [custome-action]
    uses: ./.github/workflows/common.yaml
    with:
      name: "call_job!!!!!!"
  
