name: ci-pipeline
on: [push]

env:
  IMAGE: ghcr.io/issei-fujimoto-accelia/nginx-1.21.3:v1.0

jobs:
  check-conf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 
        
      - name: run
        run: pwd && ls
      - name: 
        run: cd .github/workflows/mock && docker-compose up -d


  # check-conf:                  
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2        
        
  #     - name: Log in to registry
  #       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     - name: pull-image
  #       run: docker pull $IMAGE

 
  # check-conf2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     - name: Log in to registry
  #       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     - name: docker run
  #       run: cd ./mock && docker-compose up -d

  #     - name: check nginx conf
  #       run: docker run --net=mock-net -v $(pwd)/k8s/nginx/resources/nginx/:/nginx/ $IMAGE nginx -t
  #       run: docker run --net=mock-net -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf nginx:1.21.3 nginx -t



