name: docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        run: |
          docker-compose up -d
      - name: ps
        shell: bash
        run: |
          docker ps  
      - name: test-curl-in-steps
        shell: bash
        run: |
          curl localhost:18888
