name: docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compose-run
        shell: bash
        run: |
          docker-compose up -d
      - name: ps
        shell: bash
        run: |
          docker ps
      - name: Test
        run: docker run --network container:app appropriate/curl -s --retry 10 --retry-connrefused http://localhost:18888/
      - name: test-curl-in-steps
        shell: bash
        run: |
          curl localhost:18888

  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: test-curl-another-steps
        shell: bash
        run: |
          curl localhost:18888

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: compose-run
        shell: bash
        run: |
          curl --silent --fail --output /dev/null --head localhost:18888
