name: docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        run: |
          docker-compose up -d
      - name: ps
        shell: bash
        run: |
          docker ps
      - name: test-curl-in-steps1
        run: docker run --net golang_actions_test_default appropriate/curl  --silent --fail --output /dev/null --head app:18888/     
