name: fail-test
on: [push]

jobs:
  success:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: success
        shell: bash
        run: |
          echo success1
          
      - name: fail
        shell: bash
        run: |
          exit 7
          
      - name: success
        shell: bash
        run: |
          echo success2
  
  check-conf:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: fail
        shell: bash
        run: |
          exit 7
          
  deploy-step:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: deploy
        shell: bash
        run: |
          echo success3
