name: static check
on: [push, pull_request]

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: ./actions/
      with:
        command: imports
        token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: ./actions/
      with:
        run: lint
        token: ${{ secrets.GITHUB_TOKEN }}
