name: static check
on: [push, pull_request]

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: issei-fujimoto-accelia/github_actions_go_test@master
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}
