name: static check
on: [push, pull_request]

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      uses: ./
      with:
        command: imports
        token: ${{ secrets.GITHUB_TOKEN }}
